import Header from '@/components/Header'
import '../globals.css'
import AdminNavbar from '@/components/admin-components/AdminNavbar'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <section>
        <div className='grid grid-cols-5 gap-4'>
            <AdminNavbar/>
            {children}
        </div>
      </section>
  )
}